# Définissez une variante d'un GRID WORLD sous la forme d'un MDP et évaluez différentes stratégies sur cette environnement.

Le grid world est une grille de 5x5 cases (5 lignes de 5 colonnes) sur laquelle l'agent peut évoluer, il commence généralement sur la première ligne, première colonne. L'agent possède 4 actions possibles (gauche, droite, haut, bas). Si jamais l'agent atteint la dernière case de la première ligne => état terminal avec reward de -3. Si jamais l'agent atteint la dernière case de la dernière ligne => état terminal avec reward de 1. Si l'agent essaye de se déplacer en dehors des bords de la grille => état terminal avec score de -1.

# Grid World avec vecteurs au lieu de matrices

In [1]:
#S = [ 0,  1,  2,  3,  4,  5,  6,   LIGNE 1
#      7,  8,  9, 10, 11, 12, 13,   LIGNE 2
#     14, 15, 16, 17, 18, 19, 20,   LIGNE 3
#     21, 22, 23, 24, 25, 26, 27,   LIGNE 4
#     28, 29, 30, 31, 32, 33, 34,   LIGNE 5
#     35, 36, 37, 38, 39, 40, 41,   LIGNE 6
#     42, 43, 44, 45, 46, 47, 48]   LIGNE 7     A = [0, 1, 2, 3] # left right up down

import numpy as np

S = [i for i in range(49)]
A = [0, 1, 2, 3] # left right up down
R = [-3, -1, 0, 1] 
T = [0, 1, 2, 3, 4, 5, 6, 7, 12, 13, 14, 20, 21, 27, 28, 34, 35, 40, 41, 42, 43, 44, 45, 46, 47, 48]

p = np.zeros((len(S), len(A), len(S), len(R))) # S, A, S_p, R

In [2]:
for s in range(len(S)):
  for a in range(len(A)):
    for s_p in range(len(S)):
      for r in range(len(R)):
      

        # actions terminales :
        # si on monte depuis la premiere ligne :
        if 7 < s < 12 and a == 2 and s_p == s - 7 and R[r] == -1 :
          p[s, a, s_p, r] = 1.0
        # si on descend depuis la derniere ligne :
        if 35 < s < 40 and a == 3 and s_p == s + 7 and R[r] == -1 :
          p[s, a, s_p, r] = 1.0
        # si on va à gauche depuis la première colonne :
        if s % 7 == 1 and 7 < s < 37 and a == 0 and s_p == s - 1 and R[r] == -1 :
          p[s, a, s_p, r] = 1.0
        # si on va à droite depuis la dernière colonne :
        if s % 7 == 5 and 7 < s < 37 and a == 1 and s_p == s + 1 and R[r] == -1 :
          p[s, a, s_p, r] = 1.0
            
        # actions banales :    
        # si on est sur la premiere ligne:
        # si on descend
        if 7 < s < 12 and a == 3 and s_p == s + 7 and R[r] == 0 :
          p[s, a, s_p, r] = 1.0
        # si on va à gauche
        if 8 < s < 12 and a == 0 and s_p == s - 1 and R[r] == 0 :
          p[s, a, s_p, r] = 1.0
        # si on va à droite
        if 7 < s < 11 and a == 1 and s_p == s + 1 and R[r] == 0 :
          p[s, a, s_p, r] = 1.0


        # si on est sur la deuxième ligne:
        # si on monte
        if 14 < s < 19 and a == 2 and s_p == s - 7 and R[r] == 0 :
          p[s, a, s_p, r] = 1.0
        # si on descend
        if 14 < s < 20 and a == 3 and s_p == s + 7 and R[r] == 0 :
          p[s, a, s_p, r] = 1.0
        # si on va à droite
        if 14 < s < 19 and a == 1 and s_p == s + 1 and R[r] == 0 :
          p[s, a, s_p, r] = 1.0
        # si on va à gauche
        if 15 < s < 20 and a == 0 and s_p == s - 1 and R[r] == 0 :
          p[s, a, s_p, r] = 1.0

#S = [ 0,  1,  2,  3,  4,  5,  6,   LIGNE 0
#      7,  8,  9, 10, 11, 12, 13,   LIGNE 1
#     14, 15, 16, 17, 18, 19, 20,   LIGNE 2
#     21, 22, 23, 24, 25, 26, 27,   LIGNE 3
#     28, 29, 30, 31, 32, 33, 34,   LIGNE 4
#     35, 36, 37, 38, 39, 40, 41,   LIGNE 5
#     42, 43, 44, 45, 46, 47, 48]   LIGNE 6     A = [0, 1, 2, 3] # left right up down        
        
        # si on est sur la troisième ligne:
        # si on monte
        if 21 < s < 27 and a == 2 and s_p == s - 7 and R[r] == 0 :
          p[s, a, s_p, r] = 1.0
        # si on descend
        if 21 < s < 27 and a == 3 and s_p == s + 7 and R[r] == 0 :
          p[s, a, s_p, r] = 1.0
        # si on va à gauche
        if 22 < s < 27 and a == 0 and s_p == s - 1 and R[r] == 0 :
          p[s, a, s_p, r] = 1.0
        # si on va à droite
        if 21 < s < 26 and a == 1 and s_p == s + 1 and R[r] == 0 :
          p[s, a, s_p, r] = 1.0
          
        
        # si on est sur la quatrième ligne:
        # si on monte
        if 28 < s < 34 and a == 2 and s_p == s - 7 and R[r] == 0 :
          p[s, a, s_p, r] = 1.0
        # si on descend
        if 28 < s < 33 and a == 3 and s_p == s + 7 and R[r] == 0 :
          p[s, a, s_p, r] = 1.0 
        # si on va à gauche
        if 29 < s < 34 and a == 0 and s_p == s - 1 and R[r] == 0 :
          p[s, a, s_p, r] = 1.0 
        # si on va à droite
        if 28 < s < 33 and a == 1 and s_p == s + 1 and R[r] == 0 :
          p[s, a, s_p, r] = 1.0
          
        
        # si on est sur la dernière ligne
        # si on monte
        if 35 < s < 40 and a == 2 and s_p == s - 7 and R[r] == 0 :
          p[s, a, s_p, r] = 1.0
        # si on va à gauche
        if 36 < s < 40 and a == 0 and s_p == s - 1 and R[r] == 0 :
          p[s, a, s_p, r] = 1.0
        # si on va à droite
        if 35 < s < 39 and a == 0 and s_p == s - 1 and R[r] == 0 :
          p[s, a, s_p, r] = 1.0
          

# coup spéciaux terminaux : 

p[11][1][12][0] = 1.0
p[19][2][12][0] = 1.0
p[39][1][40][3] = 1.0
p[33][3][40][3] = 1.0

In [4]:
p[16]

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0.,

In [11]:
def naive_policy_iteration():
  theta = 0.00001
  gamma = 0.999

  V = np.random.random(len(S))
  for s in T:
    V[s] = 0.0
  Pi = np.random.choice(A, len(S), True)

  while True:
    # Policy evaluation
    while True:
      delta = 0
      for s in range(len(S)):
        v = V[s]
        total = 0
        for s_p in range(len(S)):
          for r in range(len(R)):
            total += p[s, Pi[s], s_p, r] * (R[r] + 0.999 * V[s_p])
        V[s] = total
        delta = np.maximum(delta, np.abs(v - V[s]))
      if delta < theta:
        break

    # Policy improvement
    policy_stable = True

    for s in S:
      if s in T:
        continue

      old_action = Pi[s]

      # Compute Arg Max a
      argmax_a = None
      max_a = -999999999

      for a in A:
        total = 0.0

        for s_p in S:
          for r_index in range(len(R)):
            total += p[s, a, s_p, r_index] * (R[r_index] + gamma * V[s_p])

        if argmax_a is None or total >= max_a:
          argmax_a = a
          max_a = total

      Pi[s] = argmax_a

      if old_action != Pi[s]:
        policy_stable = False


    if policy_stable:
      break

  return Pi

In [12]:
tab = naive_policy_iteration()

In [5]:
print(tab.reshape(7,7))

[[0 1 0 2 2 1 3]
 [2 3 3 3 3 2 0]
 [0 3 3 3 3 3 0]
 [0 3 3 3 3 3 3]
 [2 1 1 1 3 3 2]
 [3 2 2 2 1 3 3]
 [2 0 3 1 1 1 2]]


In [13]:
from colorama import Fore, Style

def print_grid_with_color(grid):
    for row in grid:
        for cell in row:
            if cell == 'X':
                print(Fore.RED + cell, end=' ')
            elif cell == 'I':
                print(Fore.MAGENTA + cell, end=' ')
            elif cell == 'O':
                print(Fore.YELLOW + cell, end=' ')
        print(Style.RESET_ALL)  # Réinitialiser la couleur après chaque ligne
        
# Fonction pour exécuter le jeu
def run_game(Pi, start_row, start_col):
    # Créez la grille de jeu 6x7 remplie de 0
    grid = np.zeros((7, 7), dtype=str)

    # Initialisez les bords de la grille avec 'I'
    grid[:, 0] = 'I'  # première colonne
    grid[:, 6] = 'I'  # dernière colonne
    grid[0, :] = 'I'  # première ligne
    grid[6, :] = 'I'  # dernière ligne
    grid[1:6, 1:6] = 'O' # autres lignes

    # Position de départ
    current_row, current_col = start_row, start_col

    print("Position de départ :\n")
    # Mettez à jour la grille avec le "X" de la nouvelle position
    grid[current_row, current_col] = 'X'

    # Affichez la grille mise à jour
    print_grid_with_color(grid)
    print('\n')
    print("-------------\n")

    # Exécutez le jeu étape par étape
    while True:
        # Supprimez le "X" du départ s'il existe
        grid[current_row, current_col] = 'O'

        print("Position actuelle : ({}, {})\n".format(current_row, current_col))
        action = Pi[current_row * 7 + current_col]  # Convertir les coordonnées en indice unique

        # Mettez à jour la position en fonction de l'action
        if action == 0:  # left
            current_col = max(current_col - 1, 1)
        elif action == 1:  # right
            current_col = min(current_col + 1, 5)
        elif action == 2:  # up
            current_row = max(current_row - 1, 1)
        elif action == 3:  # down
            current_row = min(current_row + 1, 5)

        # Mettez à jour la grille avec le "X" de la nouvelle position
        grid[current_row, current_col] = 'X'

        # Affichez la grille mise à jour
        print_grid_with_color(grid)
        print('\n')
        print('-------------------\n')

        # Si la position actuelle est terminale, arrêtez le jeu
        if (current_row, current_col) in [(1, 5), (5, 5)]:
            print("Position terminale atteinte. Le jeu est terminé.")
            break


In [14]:
run_game(tab, 1, 1)

Position de départ :

I I I I I I I 
I X O O O O I 
I O O O O O I 
I O O O O O I 
I O O O O O I 
I O O O O O I 
I I I I I I I 


-------------

Position actuelle : (1, 1)

I I I I I I I 
I O O O O O I 
I X O O O O I 
I O O O O O I 
I O O O O O I 
I O O O O O I 
I I I I I I I 


-------------------

Position actuelle : (2, 1)

I I I I I I I 
I O O O O O I 
I O O O O O I 
I X O O O O I 
I O O O O O I 
I O O O O O I 
I I I I I I I 


-------------------

Position actuelle : (3, 1)

I I I I I I I 
I O O O O O I 
I O O O O O I 
I O O O O O I 
I X O O O O I 
I O O O O O I 
I I I I I I I 


-------------------

Position actuelle : (4, 1)

I I I I I I I 
I O O O O O I 
I O O O O O I 
I O O O O O I 
I O X O O O I 
I O O O O O I 
I I I I I I I 


-------------------

Position actuelle : (4, 2)

I I I I I I I 
I O O O O O I 
I O O O O O I 
I O O O O O I 
I O O X O O I 
I O O O O O I 
I I I I I I I 


-------------------

Position actuelle : (4, 3)

I I I I I I I 
I O O O O O I 
I O O O O O I 
I O