In [1]:
import numpy as np

In [ ]:
#personne a joué
#PP -- PP FP CP
#PF -- PP FP CP
#PC -- PP FP CP
#FP -- PF FF CF
#FF -- PF FF CF
#FC -- PF FF CF
#CP -- PC FC CC
#CF -- PC FC CC
#CC -- PC FC CC
#PPPP
#PPFP
#PPCP
#..

In [1]:
import numpy as np
S = [i for i in range(37)]
A = [0, 1, 2] # P F C
R = [-1, 0, 1]
T = [i for i in range(10, 37)]
p = np.zeros((len(S), len(A), len(S), len(R)))

In [19]:
p[0][0][1][1] = 1/3 # PP
p[0][0][2][0] = 1/3 # PF
p[0][0][3][2] = 1/3 # PC

p[0][1][4][2] = 1/3 # FP
p[0][1][5][1] = 1/3 # FF
p[0][1][6][0] = 1/3 # FC

p[0][2][7][0] = 1/3 # CP
p[0][2][8][2] = 1/3 # CF
p[0][2][9][1] = 1/3 # CC
###############
p[1][0][10][1] = 1.0 # PP PP
p[1][1][11][2] = 1.0 # PP FP
p[1][2][12][0] = 1.0 # PP CP

p[2][0][13][1] = 1.0 # PF PP
p[2][1][14][2] = 1.0 # PF FP
p[2][2][15][0] = 1.0 # PF CP

p[3][0][16][1] = 1.0 # PC PP
p[3][1][17][2] = 1.0 # PC FP
p[3][2][18][0] = 1.0 # PC CP
###############
p[4][0][19][0] = 1.0 # FP PF
p[4][1][20][1] = 1.0 # FP FF
p[4][2][21][2] = 1.0 # FP CF

p[5][0][22][0] = 1.0 # FF PF
p[5][1][23][1] = 1.0 # FF FF
p[5][2][24][2] = 1.0 # FF CF

p[6][0][25][0] = 1.0 # FC PF
p[6][1][26][1] = 1.0 # FC FF
p[6][2][27][2] = 1.0 # FC CF
###############
p[7][0][28][2] = 1.0 # CP PC
p[7][1][29][0] = 1.0 # CP FC
p[7][2][30][1] = 1.0 # CP CC

p[8][0][31][2] = 1.0 # CF PC
p[8][1][32][0] = 1.0 # CF FC
p[8][2][33][1] = 1.0 # CF CC

p[9][0][34][2] = 1.0 # CC PC
p[9][1][35][0] = 1.0 # CC FC
p[9][2][36][1] = 1.0 # CC CC

In [20]:
def naive_policy_iteration():
  theta = 0.00001
  gamma = 0.8

  V = np.random.random(len(S))
  for s in T:
    V[s] = 0.0
  Pi = np.random.choice(A, len(S), True)

  while True:
    # Policy evaluation
    while True:
      delta = 0
      for s in range(len(S)):
        v = V[s]
        total = 0
        for s_p in range(len(S)):
          for r in range(len(R)):
            total += p[s, Pi[s], s_p, r] * (R[r] + 0.999 * V[s_p])
        V[s] = total
        delta = np.maximum(delta, np.abs(v - V[s]))
      if delta < theta:
        break

    # Policy improvement
    policy_stable = True

    for s in S:
      if s in T:
        continue

      old_action = Pi[s]

      # Compute Arg Max a
      argmax_a = None
      max_a = -999999999

      for a in A:
        total = 0.0

        for s_p in S:
          for r_index in range(len(R)):
            total += p[s, a, s_p, r_index] * (R[r_index] + gamma * V[s_p])

        if argmax_a is None or total >= max_a:
          argmax_a = a
          max_a = total

      Pi[s] = argmax_a

      if old_action != Pi[s]:
        policy_stable = False


    if policy_stable:
      break

  return Pi

In [21]:
for i in range(100):
    truc = naive_policy_iteration()
    print(truc)

[2 1 1 1 2 2 2 0 0 0 2 1 0 0 2 2 0 0 0 2 0 0 2 0 2 0 0 1 0 2 0 0 2 0 1 0 0]
[2 1 1 1 2 2 2 0 0 0 2 1 0 1 0 0 0 1 1 0 2 2 0 0 2 0 1 2 0 1 1 1 1 1 2 0 1]
[2 1 1 1 2 2 2 0 0 0 1 1 0 0 0 2 2 1 2 0 1 0 0 1 0 2 2 2 1 0 1 2 0 0 0 1 0]
[2 1 1 1 2 2 2 0 0 0 1 1 2 0 0 0 0 1 0 1 2 2 1 2 1 1 1 2 1 0 2 1 0 2 2 1 2]
[2 1 1 1 2 2 2 0 0 0 0 1 0 2 2 0 0 1 2 2 2 2 0 1 0 0 1 2 0 2 2 1 1 1 2 2 1]
[2 1 1 1 2 2 2 0 0 0 1 0 1 2 2 2 0 2 0 0 0 1 1 2 0 1 1 0 1 2 1 0 0 2 0 0 0]
[2 1 1 1 2 2 2 0 0 0 1 2 0 1 1 1 0 2 2 2 2 0 2 0 0 2 0 1 0 0 1 2 0 1 0 2 2]
[2 1 1 1 2 2 2 0 0 0 2 0 2 2 2 0 0 0 0 1 0 1 1 2 0 2 2 2 0 2 0 1 1 1 0 1 1]
[2 1 1 1 2 2 2 0 0 0 1 2 2 1 1 2 2 2 0 0 0 2 1 1 2 0 2 0 2 1 2 2 1 0 1 1 1]
[2 1 1 1 2 2 2 0 0 0 0 2 1 0 2 0 2 2 0 2 0 2 2 1 0 2 1 2 0 1 1 2 2 1 0 0 2]
[2 1 1 1 2 2 2 0 0 0 1 0 1 2 2 1 2 2 0 2 0 1 1 1 0 2 1 0 1 1 0 0 1 2 1 1 0]
[2 1 1 1 2 2 2 0 0 0 0 1 0 0 2 0 1 2 0 0 1 2 1 2 0 2 0 2 2 2 2 0 1 2 2 1 1]
[2 1 1 1 2 2 2 0 0 0 2 2 0 0 0 1 2 2 2 1 2 2 2 2 2 0 2 0 1 0 2 2 0 0 2 2 1]
[2 1 1 1 2 2

In [13]:
print(truc)

[2 1 1 1 2 2 2 0 0 0 1 0 2 1 0 1 2 2 1 1 0 0 2 2 2 1 1 2 0 0 2 2 0 0 0 2 0]
