In [1]:
import numpy as np

## Première approche

In [2]:
#               bot          !          
#            P   F   C       !
#        P   0  -1   1       !
# nous   F   1   0  -1       !
#        C  -1   1   0       !
#                            !
#      matrice pour nous     !

S = [0, 1, 2] # pierre, feuille, ciseaux
A = [0, 1, 2] # pierre, feuille, ciseaux
R = [-2, -1, 0, 1, 2] # reward potentiel à la fin des deux manches
T = [0, 1, 2] # on finit sur pierre feuille ou ciseaux

p = np.zeros((len(S), len(A), len(S), len(R))) # S, A, S_p, R

In [3]:
for s in range(len(S)):
    for a in range(len(A)):
        for s_p in range(len(S)):
            for r in range(len(R)):
                # on a joué pierre tous les deux , donc j'ai un reward de 0
                # il joue donc pierre le coup suivant
                # je gagne ensuite donc je joue feuille
                if s == 0 and a == 1 and s_p == 1 and R[r] == 1:
                    p[s][a][s_p][r] = 1.0
                # je perds ensuite, donc je joue ciseaux
                if s == 0 and a == 2 and s_p == 2 and R[r] == -1:
                    p[s][a][s_p][r] = 1.0
                # je draw ensuite donc je joue pierre encore
                if s == 0 and a == 0 and s_p == 0 and R[r] == 0:
                    p[s][a][s_p][r] = 1.0
                    
                # j'ai joué pierre, il a joué feuille, donc j'ai perdu la premiere manche
                # il joue donc pierre au tour suivant
                # je gagne ensuite donc je joue feuille
                if s == 0 and a == 1 and s_p == 1 and R[r] == 0:
                    p[s][a][s_p][r] = 1.0
                # je perds ensuite, donc je joue ciseaux
                if s == 0 and a == 2 and s_p == 2 and R[r] == -2:
                    p[s][a][s_p][r] = 1.0
                # je draw ensuite, donc je joue pierre
                if s == 0 and a == 0 and s_p == 0 and R[r] == -1:
                    p[s][a][s_p][r] = 1.0
                    
                # j'ai joué pierre et il a joué ciseaux, donc j'ai gagné la première manche
                # il joue donc pierre au tour suivant
                # je gagne la 2em manche, donc je joue feuille
                if s == 0 and a == 1 and s_p == 1 and R[r] == 2:
                    p[s][a][s_p][r] = 1.0
                # je perds la 2em manche, donc je joue ciseaux
                if s == 0 and a == 2 and s_p == 2 and R[r] == 0:
                    p[s][a][s_p][r] = 1.0
                # je draw la 2em manche, donc je joue pierre
                if s == 0 and a == 0 and s_p == 0 and R[r] == 1:
                    p[s][a][s_p][r] = 1.0
                    
        
                # on a joué feuille tous les deux , donc j'ai un reward de 0
                # il joue donc feuille le coup suivant
                # je gagne ensuite donc je joue ciseaux
                if s == 1 and a == 2 and s_p == 2 and R[r] == 1:
                    p[s][a][s_p][r] = 1.0
                # je perds ensuite, donc je joue pierre
                if s == 1 and a == 0 and s_p == 0 and R[r] == -1:
                    p[s][a][s_p][r] = 1.0
                # je draw ensuite donc je joue feuille encore
                if s == 1 and a == 1 and s_p == 1 and R[r] == 0:
                    p[s][a][s_p][r] = 1.0
                    
                # j'ai joué feuille, il a joué ciseaux, donc j'ai perdu la premiere manche
                # il joue donc feuille au tour suivant
                # je gagne ensuite donc je joue ciseaux
                if s == 1 and a == 2 and s_p == 2 and R[r] == 0:
                    p[s][a][s_p][r] = 1.0
                # je perds ensuite, donc je joue pierre
                if s == 1 and a == 0 and s_p == 0 and R[r] == -2:
                    p[s][a][s_p][r] = 1.0
                # je draw ensuite, donc je joue feuille
                if s == 1 and a == 1 and s_p == 1 and R[r] == -1:
                    p[s][a][s_p][r] = 1.0
                    
                # j'ai joué feuille et il a joué pierre, donc j'ai gagné la première manche
                # il joue donc feuille au tour suivant
                # je gagne la 2em manche, donc je joue ciseaux
                if s == 1 and a == 2 and s_p == 2 and R[r] == 2:
                    p[s][a][s_p][r] = 1.0
                # je perds la 2em manche, donc je joue pierre
                if s == 1 and a == 0 and s_p == 0 and R[r] == 0:
                    p[s][a][s_p][r] = 1.0
                # je draw la 2em manche, donc je joue feuille
                if s == 1 and a == 1 and s_p == 1 and R[r] == 1:
                    p[s][a][s_p][r] = 1.0
                    
                # ----------------------------
                #S = [0, 1, 2] # pierre, feuille, ciseaux
                #A = [0, 1, 2] # pierre, feuille, ciseaux
                #R = [-2, -1, 0, 1, 2] 
                
                # on a joué ciseaux tous les deux , donc j'ai un reward de 0
                # il joue donc ciseaux le coup suivant
                # je gagne ensuite donc je joue pierre
                if s == 2 and a == 0 and s_p == 0 and R[r] == 1:
                    p[s][a][s_p][r] = 1.0
                # je perds ensuite, donc je joue feuille
                if s == 2 and a == 1 and s_p == 1 and R[r] == -1:
                    p[s][a][s_p][r] = 1.0
                # je draw ensuite donc je joue ciseaux encore
                if s == 2 and a == 2 and s_p == 2 and R[r] == 0:
                    p[s][a][s_p][r] = 1.0
                    
                # j'ai joué ciseaux, il a joué pierre, donc j'ai perdu la premiere manche
                # il joue donc ciseaux au tour suivant
                # je gagne ensuite donc je joue pierre
                if s == 2 and a == 0 and s_p == 0 and R[r] == 0:
                    p[s][a][s_p][r] = 1.0
                # je perds ensuite, donc je joue feuille
                if s == 2 and a == 1 and s_p == 1 and R[r] == -2:
                    p[s][a][s_p][r] = 1.0
                # je draw ensuite, donc je joue ciseaux
                if s == 2 and a == 2 and s_p == 2 and R[r] == -1:
                    p[s][a][s_p][r] = 1.0
                    
                # j'ai joué ciseaux et il a joué feuille, donc j'ai gagné la première manche
                # il joue donc ciseaux au tour suivant
                # je gagne la 2em manche, donc je joue pierre
                if s == 2 and a == 0 and s_p == 0 and R[r] == 2:
                    p[s][a][s_p][r] = 1.0
                # je perds la 2em manche, donc je joue feuille
                if s == 2 and a == 1 and s_p == 1 and R[r] == 0:
                    p[s][a][s_p][r] = 1.0
                # je draw la 2em manche, donc je joue ciseaux
                if s == 2 and a == 2 and s_p == 2 and R[r] == 1:
                    p[s][a][s_p][r] = 1.0

In [5]:
def naive_policy_iteration():
  theta = 0.00001
  gamma = 0.999

  V = np.random.random(len(S))
  for s in T:
    V[s] = 0.0
  Pi = np.random.choice(A, len(S), True)

  while True:
    # Policy evaluation
    while True:
      delta = 0
      for s in range(len(S)):
        v = V[s]
        total = 0
        for s_p in range(len(S)):
          for r in range(len(R)):
            total += p[s, Pi[s], s_p, r] * (R[r] + 0.999 * V[s_p])
        V[s] = total
        delta = np.maximum(delta, np.abs(v - V[s]))
      if delta < theta:
        break

    # Policy improvement
    policy_stable = True

    for s in S:
      if s in T:
        continue

      old_action = Pi[s]

      # Compute Arg Max a
      argmax_a = None
      max_a = -999999999

      for a in A:
        total = 0.0

        for s_p in S:
          for r_index in range(len(R)):
            total += p[s, a, s_p, r_index] * (R[r_index] + gamma * V[s_p])

        if argmax_a is None or total >= max_a:
          argmax_a = a
          max_a = total

      Pi[s] = argmax_a

      if old_action != Pi[s]:
        policy_stable = False


    if policy_stable:
      break

  return Pi

In [6]:
tab = naive_policy_iteration()

/var/folders/0n/1m9037js4bl7nx4mrwxcp9sr0000gn/T/ipykernel_12818/2042133684.py:19: RuntimeWarning: overflow encountered in scalar add
  total += p[s, Pi[s], s_p, r] * (R[r] + 0.999 * V[s_p])
/var/folders/0n/1m9037js4bl7nx4mrwxcp9sr0000gn/T/ipykernel_12818/2042133684.py:19: RuntimeWarning: invalid value encountered in scalar multiply
  total += p[s, Pi[s], s_p, r] * (R[r] + 0.999 * V[s_p])


KeyboardInterrupt: 

## Seconde approche

In [2]:
import numpy as np
S = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
# 0 = on perd au premier round et l'adversaire joue ensuite pierre
# 1 = on perd au premier round et l'adversaire joue ensuite feuille
# 2 = on perd au premier round et l'adversaire joue ensuite ciseaux
# 3 = on draw au premier round et l'adversaire joue ensuite pierre
# 4 = on draw au premier round et l'adversiare joue ensuite feuille
# 5 = on draw au premier round et l'adversaire joue ensuite ciseaux
# 6 = on gagne au premier round et l'adversaire joue ensuite pierre
# 7 = on gagne au premier round et l'adversaire joue ensuite feuille
# 8 = on gagne au premier round et l'adversaire joue ensuite ciseaux
# rien

A = [0, 1, 2] # pierre, feuille, ciseaux

R = [-2, -1, 0, 1, 2] # reward total potentiel à la fin du jeu
T = [0, 1, 2] # on finit forcement sur pierre feuille ciseaux

p = np.zeros((len(S), len(A), len(S), len(R)))

In [ ]:
personne a joué
PP -- PP FP CP
PF -- PP FP CP
PC -- PP FP CP
FP -- PF FF CF
FF -- PF FF CF
FC -- PF FF CF
CP -- PC FC CC
CF -- PC FC CC
CC -- PC FC CC
PPPP
PPFP
PPCP
..

In [1]:
import numpy as np
S = [i for i in range(37)]
A = [0, 1, 2] # P F C
R = [-1, 0, 1]
T = [i for i in range(10, 37)]
p = np.zeros((len(S), len(A), len(S), len(R)))

In [19]:
p[0][0][1][1] = 1/3 # PP
p[0][0][2][0] = 1/3 # PF
p[0][0][3][2] = 1/3 # PC

p[0][1][4][2] = 1/3 # FP
p[0][1][5][1] = 1/3 # FF
p[0][1][6][0] = 1/3 # FC

p[0][2][7][0] = 1/3 # CP
p[0][2][8][2] = 1/3 # CF
p[0][2][9][1] = 1/3 # CC
###############
p[1][0][10][1] = 1.0 # PP PP
p[1][1][11][2] = 1.0 # PP FP
p[1][2][12][0] = 1.0 # PP CP

p[2][0][13][1] = 1.0 # PF PP
p[2][1][14][2] = 1.0 # PF FP
p[2][2][15][0] = 1.0 # PF CP

p[3][0][16][1] = 1.0 # PC PP
p[3][1][17][2] = 1.0 # PC FP
p[3][2][18][0] = 1.0 # PC CP
###############
p[4][0][19][0] = 1.0 # FP PF
p[4][1][20][1] = 1.0 # FP FF
p[4][2][21][2] = 1.0 # FP CF

p[5][0][22][0] = 1.0 # FF PF
p[5][1][23][1] = 1.0 # FF FF
p[5][2][24][2] = 1.0 # FF CF

p[6][0][25][0] = 1.0 # FC PF
p[6][1][26][1] = 1.0 # FC FF
p[6][2][27][2] = 1.0 # FC CF
###############
p[7][0][28][2] = 1.0 # CP PC
p[7][1][29][0] = 1.0 # CP FC
p[7][2][30][1] = 1.0 # CP CC

p[8][0][31][2] = 1.0 # CF PC
p[8][1][32][0] = 1.0 # CF FC
p[8][2][33][1] = 1.0 # CF CC

p[9][0][34][2] = 1.0 # CC PC
p[9][1][35][0] = 1.0 # CC FC
p[9][2][36][1] = 1.0 # CC CC

In [20]:
def naive_policy_iteration():
  theta = 0.00001
  gamma = 0.8

  V = np.random.random(len(S))
  for s in T:
    V[s] = 0.0
  Pi = np.random.choice(A, len(S), True)

  while True:
    # Policy evaluation
    while True:
      delta = 0
      for s in range(len(S)):
        v = V[s]
        total = 0
        for s_p in range(len(S)):
          for r in range(len(R)):
            total += p[s, Pi[s], s_p, r] * (R[r] + 0.999 * V[s_p])
        V[s] = total
        delta = np.maximum(delta, np.abs(v - V[s]))
      if delta < theta:
        break

    # Policy improvement
    policy_stable = True

    for s in S:
      if s in T:
        continue

      old_action = Pi[s]

      # Compute Arg Max a
      argmax_a = None
      max_a = -999999999

      for a in A:
        total = 0.0

        for s_p in S:
          for r_index in range(len(R)):
            total += p[s, a, s_p, r_index] * (R[r_index] + gamma * V[s_p])

        if argmax_a is None or total >= max_a:
          argmax_a = a
          max_a = total

      Pi[s] = argmax_a

      if old_action != Pi[s]:
        policy_stable = False


    if policy_stable:
      break

  return Pi

In [21]:
for i in range(100):
    truc = naive_policy_iteration()
    print(truc)

[2 1 1 1 2 2 2 0 0 0 2 1 0 0 2 2 0 0 0 2 0 0 2 0 2 0 0 1 0 2 0 0 2 0 1 0 0]
[2 1 1 1 2 2 2 0 0 0 2 1 0 1 0 0 0 1 1 0 2 2 0 0 2 0 1 2 0 1 1 1 1 1 2 0 1]
[2 1 1 1 2 2 2 0 0 0 1 1 0 0 0 2 2 1 2 0 1 0 0 1 0 2 2 2 1 0 1 2 0 0 0 1 0]
[2 1 1 1 2 2 2 0 0 0 1 1 2 0 0 0 0 1 0 1 2 2 1 2 1 1 1 2 1 0 2 1 0 2 2 1 2]
[2 1 1 1 2 2 2 0 0 0 0 1 0 2 2 0 0 1 2 2 2 2 0 1 0 0 1 2 0 2 2 1 1 1 2 2 1]
[2 1 1 1 2 2 2 0 0 0 1 0 1 2 2 2 0 2 0 0 0 1 1 2 0 1 1 0 1 2 1 0 0 2 0 0 0]
[2 1 1 1 2 2 2 0 0 0 1 2 0 1 1 1 0 2 2 2 2 0 2 0 0 2 0 1 0 0 1 2 0 1 0 2 2]
[2 1 1 1 2 2 2 0 0 0 2 0 2 2 2 0 0 0 0 1 0 1 1 2 0 2 2 2 0 2 0 1 1 1 0 1 1]
[2 1 1 1 2 2 2 0 0 0 1 2 2 1 1 2 2 2 0 0 0 2 1 1 2 0 2 0 2 1 2 2 1 0 1 1 1]
[2 1 1 1 2 2 2 0 0 0 0 2 1 0 2 0 2 2 0 2 0 2 2 1 0 2 1 2 0 1 1 2 2 1 0 0 2]
[2 1 1 1 2 2 2 0 0 0 1 0 1 2 2 1 2 2 0 2 0 1 1 1 0 2 1 0 1 1 0 0 1 2 1 1 0]
[2 1 1 1 2 2 2 0 0 0 0 1 0 0 2 0 1 2 0 0 1 2 1 2 0 2 0 2 2 2 2 0 1 2 2 1 1]
[2 1 1 1 2 2 2 0 0 0 2 2 0 0 0 1 2 2 2 1 2 2 2 2 2 0 2 0 1 0 2 2 0 0 2 2 1]
[2 1 1 1 2 2

In [13]:
print(truc)

[2 1 1 1 2 2 2 0 0 0 1 0 2 1 0 1 2 2 1 1 0 0 2 2 2 1 1 2 0 0 2 2 0 0 0 2 0]
